#ifndef MACROS_H
#define MACROS_H

#define UNIT_DEFAULT_DAMAGE_VALUE 20
#define UNIT_DEFAULT_HIT_POINTS 100
#define UNIT_DEFAULT_HIT_POINTS_LIMIT 100

#define SC_DEFAULT_DAMAGE_VALUE 10
#define SC_DEFAULT_HIT_POINTS 80
#define SC_DEFAULT_HIT_POINTS_LIMIT 80

#define WOLF_MULTIPLICATOR 1.5

#endif //MACROS_H