#ifndef MACROS_H
#define MACROS_H

#define UNIT_DAMAGE_VALUE 20
#define UNIT_HIT_POINTS 100
#define UNIT_HIT_POINTS_LIMIT 100

#define SC_DAMAGE_VALUE 10
#define SC_HIT_POINTS 80
#define SC_HIT_POINTS_LIMIT 80

#define DEMON_DAMAGE_VALUE 10
#define DEMON_HIT_POINTS 35
#define DEMON_HIT_POINTS_LIMIT 35

#define WOLF_MULTIPLICATOR 1.5

#define DEMON_NAME "Demon"

#define WARLOCK_DEMONS_LIMIT 3

#endif //MACROS_H