#ifndef MACROS_H
#define MACROS_H

#define UNIT_DAMAGE_VALUE 20
#define UNIT_HIT_POINTS 100
#define UNIT_HIT_POINTS_LIMIT 100

#define SC_DAMAGE_VALUE 10
#define SC_HIT_POINTS 80
#define SC_HIT_POINTS_LIMIT 80

#define DEMON_DAMAGE_VALUE 10
#define DEMON_HIT_POINTS 35
#define DEMON_HIT_POINTS_LIMIT 35

#define COUNTER_ATTACK_MULTIPLICATOR 0.5
#define WOLF_MULTIPLICATOR 1.5
#define NECROMANCER_MULTIPLICATOR 0.2
#define VAMPIRE_MULTIPLICATOR 0.25
#define PRIEST_MULTIPLICATOR 2
#define SPELL_MULTIPLICATOR 0.5

#define WARLOCK_DEMONS_LIMIT 3

#endif //MACROS_H